### ISSUE TITLE
Anyone can delete the paste

### ISSUE THREAD

**Issue by vitobotta** [matze/wastebin#14]
Hi, I just noticed that anyone with the link can delete the paste as there is no restriction at all. Is this intentional?

**Comment by matze** [comment]
Yes, because there is no authentication mechanism in place. But I could set a cookie to allow deletion only from the browser that made the paste. But I am not sure if that would then require a pesky cookie banner which I'd like to avoid if possible.

**Comment by vitobotta** [comment]
The cookie would work well I think

**Comment by matze** [comment]
I am not a lawyer but from what I can tell, purely functional cookies that require a site to function do not imply a cookie banner. So good chance I will start implementing this soon.

**Comment by matze** [comment]
I've pushed a branch that I will likely merge tomorrow. Works alright so far.
