### ISSUE TITLE
Minify CSS before embedding into the binary

### ISSUE THREAD

**Issue by matze** [matze/wastebin#22]
Not sure if something exists for that though. Ideally the style.css in the source tree stays readable …

**Comment by phbender** [comment]
An approach might be a [`build.rs`](https://doc.rust-lang.org/cargo/reference/build-scripts.html) file which applies some optimizations on the (embedded) assets, e.g. with [css-minify](https://github.com/Mnwa/css-minify). However, if you have the `gzip` layer, I don't know if that makes that big of a difference in performance, and also in binary size.

**Comment by matze** [comment]
Indeed, not worth it. gzipping after minification is only a few ten bytes smaller than just gzipping.
