### ISSUE TITLE
Extend syntax, including Prolog support

### ISSUE THREAD

**Issue by berezovskyi** [matze/wastebin#33]
I saw that wastebin is currently using Syntect for highlighting, which in turn relies on Sublime-2-based theme definitions. I also saw #17, which uses Tree-sitter for highlighing.

How difficult would it be to add support for Prolog code highlighting, e.g. by plugging https://github.com/BenjaminSchaaf/swi-prolog-sublime-syntax or https://github.com/Rukiza/tree-sitter-prolog into Syntect or Tree-sitter, respectively?

I am a Rust noob so far (scratch that, I have no Rust experience at all), just so that you know.

**Comment by berezovskyi** [comment]
I'd also be interested in other things like https://github.com/blake-regalia/linked-data.syntaxes but that's for later.

**Comment by matze** [comment]
I see [zola](https://github.com/getzola/zola) has additional syntaxes including Prolog, so definitely there is a way to go forward.

As indicated in #17, tree-sitter would be nice if it wasn't for the downsides: difficult set up, blow up in size and smaller number of supported languages.

**Comment by berezovskyi** [comment]
@matze vielen Dank 🤝 works wonderfully!
