### ISSUE TITLE
Cannot figure out how to set Dark Mode

### ISSUE THREAD

**Issue by netnem** [matze/wastebin#43]
How do I make the app go into dark mode?  I guessed "- WASTEBIN_DARK_MODE=1" which didn't work but I don't see any documentation to make it the default theme.

I ended up rebuilding the docker file and just copied over the dark theme into the light theme as a workaround.  Just a little strange.

**Comment by matze** [comment]
It's entirely client-side and based on your browser settings.

**Comment by netnem** [comment]
Hey no problem. I was just expecting to see a settings page where you can change the "theme" from dark / bright etc.  Feel free to close this.
