### ISSUE TITLE
Feature Request: Add Nix syntax highlighting

### ISSUE THREAD

**Issue by pinpox** [matze/wastebin#47]
I often share nix configurations and would like to have syntax highlighting for them. Any chance the language could be added to the list?
Looked a bit at how to add languages but it wasn't obvious to me, if you give me any pointers how to do it I'll try to submit a PR myself

**Comment by matze** [comment]
Nix should be in the list for a while now. https://bin.bloerg.net runs a slightly older version at the moment but it has nix language support.

**Comment by pinpox** [comment]
My bad, I was looking at an instance with an older version.
