### ISSUE TITLE
Document: How to paste from stdin

### ISSUE THREAD

**Issue by pinpox** [matze/wastebin#51]
Hey :wave: 

I mostly use pastebins when debugging sysemtems to quickly paste logs somewhere to share with coworkers. I used to have a different pastebin which allowed to do something like this:

```
cat error.log | pastebin-script
```
Which would paste that text from stdin and print a url with the created past. Is it possible to create such a command for wastebin with curl?

I saw the example for clipboards at https://github.com/matze/wastebin?tab=readme-ov-file#paste-from-clipboard but that is exactly what I need and I have not yet figured out how to make it work.

Maybe you already know how to create an alias or script for this and could document it.

**Comment by pinpox** [comment]
Answering my own question:
This bash function allows pasting by doing `cat file.txt | paste`:
```bash
past() {
	jq -Rns '{text: inputs}' | curl  -s -H 'Content-Type: application/json' \
		--data-binary @- https://wastebin.tld | jq -r '. | "wastebin.tld\(.path)"'
	}

```

**Comment by mokurin000** [comment]
> Answering my own question: This bash function allows pasting by doing `cat file.txt | paste`:
> 
> paste() {
> 	jq -Rns '{text: inputs}' | curl  -s -H 'Content-Type: application/json' \
> 		--data-binary @- https://wastebin.tld | jq -r '. | "wastebin.tld\(.path)"'
> 	}

This would result a strange HTML response contains `wrong size` on 3.0.0
my command was:

```bash
echo hello world  |  jq -Rns '{text: inputs}' | curl curl -s -H 'Content-Type: application/json' --data-binary @- http://127.0.0.1:8088/api
```
