### ISSUE TITLE
Json post endpoint

### ISSUE THREAD

**Issue by dylanjamesdev** [matze/wastebin#7]
Can you add a json post endpoint that takes content as input and returns url, so we can post to the server.

Specific use-case is posting long responses to our instance from discord bot exec command

**Comment by dylanjamesdev** [comment]
I get error 400's when posting to that endpoint, not sure why. I haven't changed any code manually.

**Comment by matze** [comment]
My bad, I had it fixed in the [preparation branch for axum 0.6](https://github.com/matze/wastebin/tree/prepare-axum-0-6) but never merged that change back into master. I will cut a 2.0.1 release soon.
